version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

